from app.api.v1.api import api_router

# Domain re-exports for clean package-level access
from app.api.v1.academics import (
    academic_content_router,
    class_router,
    class_subject_router,
    department_router,
    subject_router,
    timetable_router,
)
from app.api.v1.admissions import application_router, document_router
from app.api.v1.ai_analytics import (
    ai_analytics_router,
    ai_chat_history_router,
    user_chat_history_router,
)
from app.api.v1.assignments import (
    class_assignment_router,
    router as assignment_router,
    student_assignment_router,
    submission_router,
    teacher_assignment_router,
)
from app.api.v1.attendance import router as attendance_router
from app.api.v1.audit import (
    audit_log_router,
    audit_router,
    login_history_router,
    user_audit_router,
)
from app.api.v1.auth import (
    get_current_user,
    oauth2_scheme,
    router as auth_router,
)
from app.api.v1.communication import (
    announcement_router,
    communication_router,
    message_router,
    notification_router,
    teacher_communication_router,
    user_communication_router,
)
from app.api.v1.dashboard import router as dashboard_router
from app.api.v1.events import academic_calendar_router, event_router
from app.api.v1.exams import (
    exam_result_router,
    exam_router,
    exam_sub_router,
    report_card_router,
)
from app.api.v1.finance import (
    accountant_fee_router,
    fee_invoice_router,
    fee_structure_router,
    finance_router,
    payment_router,
    student_fee_router,
)
from app.api.v1.hostel import (
    allocation_router,
    bed_router,
    block_router,
    hostel_complaint_router,
    hostel_extra_router,
    hostel_fee_invoice_router,
    hostel_fee_structure_router,
    hostel_leave_router,
    hostel_notice_router,
    hostel_payment_router,
    hostel_router,
    hostel_setting_router,
    maintenance_router,
    mess_attendance_router,
    mess_collection_router,
    mess_expense_router,
    mess_menu_router,
    room_router,
    student_hostel_extra_router,
    student_hostel_router,
    visitor_router,
    work_order_router,
)
from app.api.v1.leaves import (
    leave_request_router,
    leave_type_router,
    user_leave_router,
)
from app.api.v1.library import (
    author_router,
    book_category_router,
    book_issue_router,
    book_router,
    fine_payment_router,
    library_report_router,
    library_router,
    library_settings_router,
    publisher_router,
    reservation_router,
    student_library_router,
)
from app.api.v1.parents import (
    parent_router,
    parent_student_router,
)
from app.api.v1.settings import settings_router
from app.api.v1.students import router as student_router
from app.api.v1.teachers import (
    teacher_router,
    teacher_subject_router,
)
from app.api.v1.transport import (
    bus_router,
    route_router,
    student_transport_detail_router,
    student_transport_router,
    transport_router,
)
from app.api.v1.users import (
    admin_router,
    user_router,
)

__all__ = [
    "api_router",
    "dashboard_router",
    "admin_router",
    "user_router",
    "department_router",
    "class_router",
    "subject_router",
    "class_subject_router",
    "teacher_subject_router",
    "timetable_router",
    "academic_content_router",
    "teacher_router",
    "parent_router",
    "student_router",
    "parent_student_router",
    "attendance_router",
    "exam_router",
    "exam_sub_router",
    "exam_result_router",
    "report_card_router",
    "assignment_router",
    "submission_router",
    "teacher_assignment_router",
    "class_assignment_router",
    "student_assignment_router",
    "announcement_router",
    "notification_router",
    "message_router",
    "communication_router",
    "user_communication_router",
    "teacher_communication_router",
    "fee_structure_router",
    "fee_invoice_router",
    "payment_router",
    "student_fee_router",
    "accountant_fee_router",
    "finance_router",
    "application_router",
    "document_router",
    "leave_type_router",
    "leave_request_router",
    "user_leave_router",
    "event_router",
    "academic_calendar_router",
    "book_category_router",
    "book_router",
    "book_issue_router",
    "student_library_router",
    "library_router",
    "author_router",
    "publisher_router",
    "reservation_router",
    "fine_payment_router",
    "library_settings_router",
    "library_report_router",
    "bus_router",
    "route_router",
    "student_transport_router",
    "student_transport_detail_router",
    "transport_router",
    "auth_router",
    "get_current_user",
    "oauth2_scheme",
    "login_history_router",
    "audit_log_router",
    "audit_router",
    "user_audit_router",
    "ai_analytics_router",
    "ai_chat_history_router",
    "user_chat_history_router",
    "block_router",
    "room_router",
    "bed_router",
    "allocation_router",
    "student_hostel_router",
    "hostel_router",
    "visitor_router",
    "hostel_fee_structure_router",
    "hostel_fee_invoice_router",
    "hostel_payment_router",
    "mess_menu_router",
    "mess_expense_router",
    "mess_collection_router",
    "mess_attendance_router",
    "maintenance_router",
    "work_order_router",
    "student_hostel_extra_router",
    "hostel_extra_router",
    "hostel_complaint_router",
    "hostel_notice_router",
    "hostel_setting_router",
    "hostel_leave_router",
    "settings_router",
]
