"""add academic content models

Revision ID: 0e8f33ba8e22
Revises: b1c2d3e4f5a6
Create Date: 2026-08-22 18:25:32.260797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8f33ba8e22'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('chapter_name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('materials_needed', sa.Text(), nullable=True),
    sa.Column('procedure_summary', sa.Text(), nullable=True),
    sa.Column('homework_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('feedback_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_drivers_bus_id'), table_name='drivers')
    op.drop_index(op.f('ix_expenses_approved_by'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_fee_installments_fee_structure_id'), table_name='fee_installments')
    op.drop_index(op.f('ix_fee_structures_class_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_student_category_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_late_fee_rules_fee_structure_id'), table_name='late_fee_rules')
    op.drop_index(op.f('ix_other_incomes_category'), table_name='other_incomes')
    op.drop_index(op.f('ix_other_incomes_income_date'), table_name='other_incomes')
    op.drop_index(op.f('ix_refund_requests_status'), table_name='refund_requests')
    op.drop_index(op.f('ix_refund_requests_student_id'), table_name='refund_requests')
    op.drop_index(op.f('ix_salaries_approved_by'), table_name='salaries')
    op.drop_index(op.f('ix_student_fee_assignments_fee_structure_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_fee_assignments_student_id'), table_name='student_fee_assignments')
    op.drop_index(op.f('ix_student_ledgers_student_id'), table_name='student_ledgers')
    op.drop_index(op.f('ix_student_ledgers_transaction_type'), table_name='student_ledgers')
    op.drop_index(op.f('ix_student_scholarships_scholarship_type_id'), table_name='student_scholarships')
    op.drop_index(op.f('ix_student_scholarships_status'), table_name='student_scholarships')
    op.drop_index(op.f('ix_student_scholarships_student_id'), table_name='student_scholarships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_scholarships_student_id'), 'student_scholarships', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_scholarships_status'), 'student_scholarships', ['status'], unique=False)
    op.create_index(op.f('ix_student_scholarships_scholarship_type_id'), 'student_scholarships', ['scholarship_type_id'], unique=False)
    op.create_index(op.f('ix_student_ledgers_transaction_type'), 'student_ledgers', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_student_ledgers_student_id'), 'student_ledgers', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_student_id'), 'student_fee_assignments', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_fee_assignments_fee_structure_id'), 'student_fee_assignments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_salaries_approved_by'), 'salaries', ['approved_by'], unique=False)
    op.create_index(op.f('ix_refund_requests_student_id'), 'refund_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_refund_requests_status'), 'refund_requests', ['status'], unique=False)
    op.create_index(op.f('ix_other_incomes_income_date'), 'other_incomes', ['income_date'], unique=False)
    op.create_index(op.f('ix_other_incomes_category'), 'other_incomes', ['category'], unique=False)
    op.create_index(op.f('ix_late_fee_rules_fee_structure_id'), 'late_fee_rules', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_student_category_id'), 'fee_structures', ['student_category_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_class_id'), 'fee_structures', ['class_id'], unique=False)
    op.create_index(op.f('ix_fee_installments_fee_structure_id'), 'fee_installments', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_expenses_expense_category_id'), 'expenses', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_expenses_approved_by'), 'expenses', ['approved_by'], unique=False)
    op.create_index(op.f('ix_drivers_bus_id'), 'drivers', ['bus_id'], unique=False)
    op.drop_table('student_feedback')
    op.drop_table('lesson_plans')
    op.drop_table('content_resources')
    op.drop_table('chapter_notes')
    # ### end Alembic commands ###
