"""add_subject_type_credits_status

Revision ID: 63ff3db91215
Revises: 0e8f33ba8e22
Create Date: 2026-09-12 20:14:14.658586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ff3db91215'
down_revision: Union[str, Sequence[str], None] = '0e8f33ba8e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('subject_type', sa.String(length=50), nullable=True))
    op.add_column('subjects', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('periods_per_week', sa.Integer(), nullable=True))
    op.add_column('subjects', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'status')
    op.drop_column('subjects', 'periods_per_week')
    op.drop_column('subjects', 'credits')
    op.drop_column('subjects', 'subject_type')
    # ### end Alembic commands ###
